{
 "title": "Wireguard",
 "description": "Metrics for Wireguard VPN",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(wireguard_received_bytes_total + wireguard_sent_bytes_total) by (allowed_ips))",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "(wireguard_latest_handshake_delay_seconds) < bool 350",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Peers History",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum by(allowed_ips) (wireguard_latest_handshake_delay_seconds) < bool 350",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Download by peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(allowed_ips) (irate(wireguard_sent_bytes_total[5m])) > 1",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Upload by peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(allowed_ips) (irate(wireguard_received_bytes_total[15m])) > 1",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  }
 ]
}